name: CI - Build LLVM Pass

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake ninja-build clang llvm lld

      - name: Configure
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build -- -j$(nproc)

      - name: Run test pass on sample IR
        run: |
          opt -load-pass-plugin ./build/SimpleStrengthReductionPass.so                       -passes=strength-reduction test/input.ll -S -o out.ll
          cat out.ll
